### ISSUE TITLE
Problem With Connections

### ISSUE THREAD

**Issue by Klotzlutscher** [PyvesB/advanced-achievements#974]
:information_source: **Basic information**

* Advanced Achievements version: 
* Minecraft version: 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 

:beetle: **Description**

 Hey, we had found a Problem.
When i used the command /aach add 100 Connections Klotzlutscher it wont add anything. It comes no error in Log and no message ingame it just dont do it.
Next Problem is , that sometimes by some people the counter for Logins doesnt go up.How do AACH get the Datas from Logins? Think from Essentials? Example: We had released the Plugin on 19.02.2021 so some
Players had Login every Day but not had get all days in the Progress bar. We had manual add it on the Databank.
https://i.imgur.com/CjP9CFB.png
https://i.imgur.com/MK9oYYS.png
But for large Playercounts its a pain in the ass to add it all manualy.
 

:page_facing_up: **Server logs**

https://i.imgur.com/W8KOwre.png

**Comment by PyvesB** [comment]
Hello @Klotzlutscher ! 👋🏻 

Please fill out all the required information in the issue template.

**Comment by Klotzlutscher** [comment]
Sorry here are the Config part -> https://i.imgur.com/ZABhYlO.png Did you need any more?

**Comment by PyvesB** [comment]
> * Advanced Achievements version:
> 
> * Minecraft version:
> 
> * [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read:
> 
> * [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:

This whole section hasn't been filled in in any of the issues you have raised.

**Comment by PyvesB** [comment]
So, this is not a bug, it's actually clearly stated in [the Wiki](https://github.com/PyvesB/advanced-achievements/wiki/Commands) that the _/aach add_ command does not work for the _Connections_ category. That being said, it's probably easy to change following the refactor from version 7.0.0, I'll see what I can do. 😉

**Comment by Klotzlutscher** [comment]
hey , then i really missed it on the wiki , my fault. i have read alot in the wiki sorry for that :D

**Comment by PyvesB** [comment]
Done, this limitation should now be lifted! 🍾

**Comment by Klotzlutscher** [comment]
Hey we have tested it.
Server Version MC: 1.16.5 Paper-547
AACH Version: 7.0.1

The Command /aach add AMOUNT Connections PLAYER does still not work.
Here is the Logfile:
[15:42:29] [Server thread/INFO]: Klotzlutscher issued server command: /aach add 100 Connections Klotzlutscherin

No Error,No warning,Nothing happens.

Could you please take a look and try to Fix it.If you need more Informations just message here. 
Best Greats Klotzlutscher

**Comment by PyvesB** [comment]
Version 7.0.1 does not yet contain the fix.

**Comment by Klotzlutscher** [comment]
Oh sorry my Fault , didnt read the changelog well enough :D
